### ISSUE TITLE
Run `inst_sge` with -noremote

### ISSUE THREAD

**Issue by cancan101** [awslabs/cfncluster-cookbook#13]
This is what [starcluster does](https://github.com/jtriley/StarCluster/blob/54a61fd0add8802e61a8c035944389fe2939be23/starcluster/plugins/sge.py#L97). Docs say:

```
TIP: Add the -noremote flag to the above commands to perform the action
     only on the current host without making any remote connections
```

**Comment by dougalb** [comment]
This has been included in cfncluster-cookbook-1.3.0, which is used by cfncluster-1.3.1
