### ISSUE TITLE
Base ami not available

### ISSUE THREAD

**Issue by kdaily** [awslabs/cfncluster-cookbook#3]
The base ami for CentOS (ami-8f6d88ef) is not available.

From https://github.com/awslabs/cfncluster/issues/29 I'm trying to customize the existing image.

**Comment by dougalb** [comment]
This is an internal image used for building CentOS 6 specifically. If you are building your own AMIs, you can use the CentOS 6 Marketplace AMIs - https://aws.amazon.com/marketplace/pp/B00NQAYLWO/ref=srh_res_product_title?ie=UTF8&sr=0-2&qid=1458593345443.

**Comment by kdaily** [comment]
Thanks!

**Comment by kdaily** [comment]
How were you able to make your images public? Did you not use the CentOS 6 AMI as base? I ran into this when finishing, using `ami-95f7e3ff` as the base:

```
Error modify AMI attributes: OperationNotPermitted: Images with marketplace product codes may not be made public.
```

**Comment by dougalb** [comment]
The base images that I use for CentOS are not AWS Marketplace images, so that we can make them public. Do you images need to be public?

**Comment by kdaily** [comment]
If possible, it would make things easier, please!

**Comment by dougalb** [comment]
Sorry, getting wires crossed. I cannot make the base AMIs public. My question is, do your AMIs need to be public?

**Comment by kdaily** [comment]
Sorry - yes, it would be preferential to make our AMIs public.

**Comment by bwbarrett** [comment]
As @dougalb said, CfnCluster doesn't make its base AMIs public.  You can either start from the public CentOS AMIs used by CfnCluster or build a CentOS AMI from scratch (which is tricky and way outside of the scope of CfnCluster support).
